/*
 * Copyright (c) 2025, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the
 * repo root or https://opensource.org/licenses/BSD-3-Clause
 */

/**
 * Console error information captured during testing.
 */
export interface ConsoleError {
  /** Error message text */
  readonly text: string;
  /** URL where the error occurred, if available */
  readonly url?: string;
}

/**
 * Network error information captured during testing.
 */
export interface NetworkError {
  /** HTTP status code */
  readonly status: number;
  /** URL that failed to load */
  readonly url: string;
  /** Description of the error */
  readonly description: string;
}

/**
 * Pattern used for filtering non-critical console errors.
 */
export type ErrorFilterPattern = string;

/**
 * Patterns for filtering out non-critical console errors.
 */
export const NON_CRITICAL_ERROR_PATTERNS: readonly ErrorFilterPattern[] = [
  // Resource loading errors (VS Code Web environment)
  'favicon.ico',
  'sourcemap',
  'webPackagePaths.js',
  'workbench.web.main.nls.js',

  // VS Code Web expected noise (IndexedDB, marketplace, extensions)
  'idbtransaction',
  'indexeddb database',
  'marketplace.visualstudio.com',
  "Activating extension 'vscode.typescript-language-features' failed",
  'CodeExpectedError',
  'Failed to load resource',
  'vscode-userdata:/user/caches/cachedconfigurations',
  'vsliveshare',
  'punycode',
  'selectedStep',
  'onWillSaveTextDocument',
  'Throttler is disposed',
  'vscode-log:',
  'tasks.log',
  'theme-defaults/themes',
  'light_modern.json',
  'Failed to fetch',
  'NO_COLOR',
  'Content Security Policy',
  'Applying inline style violates',
  'Unable to resolve resource walkThrough://',
  'SourceMembers timed out after',
  'Blocked script execution',
  'vscode-webview://',
  'Failed to write JSON test result file',
  'callback must be a function',
  'Unable to resolve nonexistent file',
  'testResults',
  'workspaceStorage',

  // LSP and language server related non-critical errors
  'Request textDocument/', // Any textDocument request can fail in web/test environments
  'Unhandled method textDocument/', // Unhandled LSP method notifications
  'Pending response rejected since connection got disposed', // LSP client shutdown race
  "Client is not running and can't be stopped", // LSP client state during teardown
  'Server initialization failed', // LSP server fails to start (e.g. in test env)
  "couldn't create connection to server", // LSP connection failure in test env
  'Connection to server got closed. Server will not be restarted', // LSP shutdown in test env
  'An unknown error occurred. Please consult the log', // VS Code generic error wrapper

  // VS Code lifecycle and shutdown related
  'Long running operations during shutdown',
  'lifecycle',
  // VS Code web contribution noise in newer builds
  'terminal.chatAgentTools',
  'ISandboxHelperService',
  'terminalSandboxService',
  'Unable to create workbench contribution',
  'remoteAgentHostService',

  // Network and connectivity (often transient)
  'hostname could not be found',

  // Grammar and syntax highlighting files (expected in web environment)
  'apex.tmLanguage',
  'grammars/apex.tmLanguage',
  'Unable to load and parse grammar',

  // VS Code webview Content Security Policy errors (expected in Electron/webview environment)
  // These are generated by VS Code's own webview infrastructure, not by the extension
  'Content Security Policy',
  'Applying inline style violates',
  'vscode-webview://',
] as const;

/**
 * Patterns for filtering out non-critical network errors.
 * These patterns match network errors that are expected in VS Code Web environment
 * and do not indicate actual problems with the extension functionality.
 */
export const NON_CRITICAL_NETWORK_PATTERNS: readonly ErrorFilterPattern[] = [
  // VS Code Web resource loading (404 errors are expected)
  'webPackagePaths.js',
  'workbench.web.main.nls.js',

  // VS Code marketplace and extension CDN
  'marketplace.visualstudio.com',
  'vscode-unpkg.net',

  // Grammar files (expected to be missing in web environment)
  'apex.tmLanguage',
  'grammars/apex.tmLanguage',
] as const;

/**
 * CSS selectors used in tests.
 */
export const SELECTORS = {
  WORKBENCH: '.monaco-workbench',
  EXPLORER: '[id="workbench.view.explorer"]',
  EDITOR_PART: '[id="workbench.parts.editor"]',
  /** Main editor area - excludes peek widget and other overlays */
  MONACO_EDITOR: '[id="workbench.parts.editor"] .monaco-editor',
  SIDEBAR: '[id="workbench.parts.sidebar"]',
  STATUSBAR: '[id="workbench.parts.statusbar"]',
  EXTENSIONS_VIEW: '[id*="workbench.view.extensions"], .extensions-viewlet',
  APEX_FILE_ICON: '.cls-ext-file-icon, .apex-lang-file-icon',
  CLS_FILE_ICON: '.cls-ext-file-icon',
  OUTLINE_TREE: '.outline-tree, .monaco-tree, .tree-explorer',
  SYMBOL_ICONS:
    '.codicon-symbol-class, .codicon-symbol-method, .codicon-symbol-field',
} as const;

/**
 * Outline view selectors for testing.
 */
export const OUTLINE_SELECTORS = [
  'text=OUTLINE',
  '.pane-header[aria-label*="Outline"]',
  '[id*="outline"]',
  '.outline-tree',
] as const;

/**
 * Interface for expected Apex symbols in outline view.
 */
export interface ExpectedApexSymbols {
  /** Name of the Apex class */
  readonly className: string;
  /** Type of the class symbol */
  readonly classType: 'class' | 'interface' | 'enum';
  /** Expected methods in the class */
  readonly methods: readonly {
    readonly name: string;
    readonly visibility?: 'public' | 'private' | 'protected' | 'global';
    readonly isStatic?: boolean;
  }[];
  /** Minimum expected total symbols (class + methods + fields) */
  readonly totalSymbols?: number;
}

/**
 * Expected symbol structure for ApexClassExample.cls file.
 * The current outline reliably exposes the top-level class; nested symbols are covered
 * by hover and go-to-definition tests instead of the outline suite.
 */
export const EXPECTED_APEX_SYMBOLS: ExpectedApexSymbols = {
  className: 'ApexClassExample',
  classType: 'class',
  methods: [
    // Current outline coverage focuses on top-level symbol stability.
  ],
  totalSymbols: 1,
};
