name: 'Get Package Lists'
description: 'Dynamically determines NPM packages and VS Code extensions in the monorepo'

outputs:
  npm-packages:
    description: 'Comma-separated list of NPM package names'
    value: ${{ steps.packages.outputs.npm-packages }}
  extensions:
    description: 'Comma-separated list of VS Code extension names'
    value: ${{ steps.packages.outputs.extensions }}
  extension-paths:
    description: 'Extension package paths for publishing'
    value: ${{ steps.packages.outputs.extension-paths }}

runs:
  using: 'composite'
  steps:
    - name: Get package lists
      id: packages
      shell: bash
      run: |
        # Get NPM packages (packages with package.json but no publisher)
        NPM_PACKAGES=""
        EXTENSIONS=""
        EXTENSION_PATHS=""
        
        for pkg in packages/*/; do
          PKG_NAME=$(basename "$pkg")
          if [ -f "$pkg/package.json" ]; then
            if grep -q '"publisher"' "$pkg/package.json"; then
              # It's a VS Code extension
              EXTENSIONS="$EXTENSIONS,$PKG_NAME"
              if [ "$PKG_NAME" = "apex-lsp-vscode-extension" ]; then
                EXTENSION_PATHS="$EXTENSION_PATHS,desktop:$pkg,web:$pkg"
              fi
            else
              # It's an NPM package
              NPM_PACKAGES="$NPM_PACKAGES,$PKG_NAME"
            fi
          fi
        done
        
        # Remove leading commas
        NPM_PACKAGES=${NPM_PACKAGES#,}
        EXTENSIONS=${EXTENSIONS#,}
        EXTENSION_PATHS=${EXTENSION_PATHS#,}
        
        echo "npm-packages=$NPM_PACKAGES" >> $GITHUB_OUTPUT
        echo "extensions=$EXTENSIONS" >> $GITHUB_OUTPUT
        echo "extension-paths=$EXTENSION_PATHS" >> $GITHUB_OUTPUT 
        echo $GITHUB_OUTPUT