/*
 * Copyright (c) 2025, salesforce.com, inc.
 * All rights reserved.
 * Licensed under the BSD 3-Clause license.
 * For full license text, see LICENSE.txt file in the
 * repo root or https://opensource.org/licenses/BSD-3-Clause
 */

/**
 * STUB FILE - Build-Time Replacement Target
 *
 * This file exports `undefined` in source/development mode.
 * During bundling (esbuild), this export is replaced with actual binary data
 * containing the StandardApexLibrary.zip contents.
 *
 * ## How It Works
 *
 * 1. Source code imports this module and gets `undefined`
 * 2. esbuild's `injectStdLibDataPlugin` intercepts the import
 * 3. Plugin reads `StandardApexLibrary.zip` and injects as Uint8Array
 * 4. Bundled code gets the actual ZIP data
 *
 * ## Build Dependencies
 *
 * - Requires: `packages/apex-parser-ast/resources/StandardApexLibrary.zip`
 * - Generated by: Standard library ZIP file
 * - Injected by: `packages/apex-ls/esbuild.config.ts`
 *
 * ## Testing
 *
 * - Unit tests run against source (stub returns undefined)
 * - E2E tests should verify bundled output contains real data
 *
 * @see packages/apex-ls/esbuild.config.ts - injectStdLibDataPlugin
 */
const stdLibData: Uint8Array | undefined = undefined;
export default stdLibData;
