name: Get Package Lists

on:
  workflow_call:
    outputs:
      npm-packages:
        description: 'List of NPM packages'
        value: ${{ jobs.get-packages.outputs.npm-packages }}
      extensions:
        description: 'List of VS Code extensions'
        value: ${{ jobs.get-packages.outputs.extensions }}
      extension-paths:
        description: 'Extension package paths'
        value: ${{ jobs.get-packages.outputs.extension-paths }}

jobs:
  get-packages:
    runs-on: ubuntu-latest
    outputs:
      npm-packages: ${{ steps.packages.outputs.npm-packages }}
      extensions: ${{ steps.packages.outputs.extensions }}
      extension-paths: ${{ steps.packages.outputs.extension-paths }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get package lists
        id: packages
        run: |
          # Get NPM packages (packages with package.json but no publisher)
          NPM_PACKAGES=""
          EXTENSIONS=""
          EXTENSION_PATHS=""

          for pkg in packages/*/; do
            PKG_NAME=$(basename "$pkg")
            if [ -f "$pkg/package.json" ]; then
              if grep -q '"publisher"' "$pkg/package.json"; then
                # It's a VS Code extension
                EXTENSIONS="$EXTENSIONS,$PKG_NAME"
                if [ "$PKG_NAME" = "apex-lsp-vscode-extension" ]; then
                  EXTENSION_PATHS="$EXTENSION_PATHS,desktop:$pkg"
                elif [ "$PKG_NAME" = "apex-lsp-vscode-extension-web" ]; then
                  EXTENSION_PATHS="$EXTENSION_PATHS,web:$pkg"
                fi
              else
                # It's an NPM package
                NPM_PACKAGES="$NPM_PACKAGES,$PKG_NAME"
              fi
            fi
          done

          # Remove leading commas
          NPM_PACKAGES=${NPM_PACKAGES#,}
          EXTENSIONS=${EXTENSIONS#,}
          EXTENSION_PATHS=${EXTENSION_PATHS#,}

          echo "npm-packages=$NPM_PACKAGES" >> $GITHUB_OUTPUT
          echo "extensions=$EXTENSIONS" >> $GITHUB_OUTPUT
          echo "extension-paths=$EXTENSION_PATHS" >> $GITHUB_OUTPUT
