name: Publish in Open VSX Registry
on:
  workflow_call:
    inputs:
      branch:
        description: 'Branch to publish from'
        required: false
        default: 'main'
        type: string
      pre-release:
        description: 'Publish as pre-release version'
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to publish from'
        required: true
        default: 'main'
        type: string
      pre-release:
        description: 'Publish as pre-release version'
        required: false
        default: false
        type: boolean

jobs:
  package:
    uses: ./.github/workflows/package.yml
    with:
      branch: ${{ inputs.branch || github.ref_name }}

  publish:
    needs: package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.inputs.branch == github.ref_name || inputs.branch == github.ref_name
    env:
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
      GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.IDEE_GH_TOKEN }}
          ref: ${{ github.event.inputs.branch || inputs.branch || github.ref }}

      - name: Download VSIX artifacts
        uses: actions/download-artifact@v4
        with:
          name: vsix-packages
          path: ./vsix-artifacts

      - name: Publish to Open VSX Registry
        run: |
          # Get the package version from package.json
          PACKAGE_VERSION=$(node -p "require('./packages/apex-lsp-vscode-extension-web/package.json').version")
          echo "Looking for web extension version: $PACKAGE_VERSION"

          # Find the VSIX file matching the package version
          VSIX_PATH=$(find ./vsix-artifacts -name "*apex-language-server-extension-web-${PACKAGE_VERSION}.vsix" | head -1)
          if [ -z "$VSIX_PATH" ]; then
            echo "Web extension VSIX file for version $PACKAGE_VERSION not found in artifacts."
            echo "Available VSIX files:"
            find ./vsix-artifacts -name "*.vsix" | sort
            exit 1
          fi
          echo "Publishing VSIX: $VSIX_PATH"

          # Add pre-release flag if needed
          PRE_RELEASE_FLAG=""
          if [ "${{ inputs.pre-release }}" = "true" ]; then
            PRE_RELEASE_FLAG="--pre-release"
            echo "Publishing as pre-release version"
          fi

          # Publish using ovsx
          npx ovsx publish "$VSIX_PATH" -p ${{ secrets.OVSX_PAT }} $PRE_RELEASE_FLAG

          echo "✅ Successfully published to OpenVSX Registry"
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
