name: Publish in Open VSX Registry
on:
  workflow_call:
    inputs:
      skip-package:
        description: 'Skip the package job if already built'
        required: false
        default: 'false'
        type: string
      branch:
        description: 'Branch to publish from'
        required: false
        default: 'main'
        type: string
      pre-release:
        description: 'Publish as pre-release version'
        required: false
        default: 'false'
        type: string
      dry-run:
        description: 'Run in dry-run mode (validate without publishing)'
        required: false
        default: 'false'
        type: string
  workflow_dispatch:
    inputs:
      skip-package:
        description: 'Skip the package job if already built'
        required: false
        default: 'false'
        type: string
      branch:
        description: 'Branch to publish from'
        required: true
        default: 'main'
        type: string
      pre-release:
        description: 'Publish as pre-release version'
        required: false
        default: 'false'
        type: string
      dry-run:
        description: 'Run in dry-run mode (validate without publishing)'
        required: false
        default: 'false'
        type: string

jobs:
  package:
    if: inputs.skip-package != 'true'
    uses: ./.github/workflows/package.yml
    with:
      branch: ${{ inputs.branch || github.ref_name }}

  publish:
    needs: package
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event.inputs.branch == github.ref_name || inputs.branch == github.ref_name
    env:
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
      GITHUB_TOKEN: ${{ secrets.IDEE_GH_TOKEN }}
    steps:
      - name: Flexible branch match (skip job if not matching)
        run: |
          BRANCH="${GITHUB_REF}"
          INPUT_BRANCH="${{ inputs.branch }}"
          EVENT_BRANCH="${{ github.event.inputs.branch }}"
          if [[ "$BRANCH" == *"$INPUT_BRANCH" ]] || [[ "$BRANCH" == *"$EVENT_BRANCH" ]]; then
            echo "Branch matches, continuing."
          else
            echo "Branch does not match, skipping job."
            exit 0
          fi

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.IDEE_GH_TOKEN }}
          ref: ${{ github.event.inputs.branch || inputs.branch || github.ref }}

      - name: Download VSIX artifacts
        uses: actions/download-artifact@v4
        with:
          name: vsix-packages
          path: ./vsix-artifacts

      - name: Setup dry-run artifacts
        if: inputs.dry-run == 'true' || github.event.inputs.dry-run == 'true'
        run: |
          mkdir -p ./vsix-artifacts
          cp ./dry-run-artifacts/*.vsix ./vsix-artifacts/ || echo "No VSIX files found"
          echo "✅ Dry-run: Using local VSIX artifacts from ./dry-run-artifacts/"

      - name: Publish to Open VSX Registry
        run: |
          # Get the package version from package.json
          PACKAGE_VERSION=$(node -p "require('./packages/apex-lsp-vscode-extension-web/package.json').version")
          echo "Looking for web extension version: $PACKAGE_VERSION"

          # Find the VSIX file matching the package version
          VSIX_PATH=$(find ./vsix-artifacts -name "*apex-language-server-extension-web-${PACKAGE_VERSION}.vsix" | head -1)
          if [ -z "$VSIX_PATH" ]; then
            echo "Web extension VSIX file for version $PACKAGE_VERSION not found in artifacts."
            echo "Available VSIX files:"
            find ./vsix-artifacts -name "*.vsix" | sort
            exit 1
          fi
          echo "Found VSIX: $VSIX_PATH"

          # Add pre-release flag if needed
          PRE_RELEASE_FLAG=""
          if [ "${{ inputs.pre-release }}" = "true" ]; then
            PRE_RELEASE_FLAG="--pre-release"
            echo "Would publish as pre-release version"
          fi

          # Check if this is a dry run
          if [ "${{ inputs.dry-run }}" = "true" ]; then
            echo "🔍 DRY RUN MODE - Would publish to OpenVSX Registry:"
            echo "  VSIX: $VSIX_PATH"
            echo "  Pre-release: ${{ inputs.pre-release }}"
            echo "  Command: npx ovsx publish \"$VSIX_PATH\" -p [PAT] $PRE_RELEASE_FLAG"
            echo "✅ Dry run completed - no actual publish performed"
          else
            echo "Publishing VSIX: $VSIX_PATH"
            # Publish using ovsx
            npx ovsx publish "$VSIX_PATH" -p ${{ secrets.OVSX_PAT }} $PRE_RELEASE_FLAG
            echo "✅ Successfully published to OpenVSX Registry"
          fi
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
